### ISSUE TITLE
Refactor run command

### ISSUE THREAD

**Issue by tejas-techstack** [acmpesuecc/SmartGC#2]
` python3 ParseInject.py UserCode.c OutCode.c references.json `

As of right now this command needs to be run to use the the smartGC. Refactor this by making it easier for the user

eg: 

` ./smartGC UserCode.c ` 
should do all the work

hint: write a shell script to do this.

**Comment by Nightwing000** [comment]
Can you assign this

**Comment by tejas-techstack** [comment]
alright im assigning you @Nightwing000 
i will be giving you 30 min as of now, based on your progress we shall extend the time if needed

**Comment by tejas-techstack** [comment]
!assign @Nightwing000 30

**Comment by Nightwing000** [comment]
thanks

**Comment by Nightwing000** [comment]
Yeah its running the code that's enough right if there's some issues with libraries and stuff I don't need to solve those right?

**Comment by tejas-techstack** [comment]
yup, as long as i can replicate your work and its correct you will get points

**Comment by tejas-techstack** [comment]
make sure once you are done you create a pull request into a new branch and not main

**Comment by tejas-techstack** [comment]
when you are done and want to create a pullrequest please send me a message so that i can confirm which branch you will need to create the pull request to @Nightwing000

**Comment by Nightwing000** [comment]
yeah i'm done

**Comment by tejas-techstack** [comment]
create the pull request to issue2

**Comment by Nightwing000** [comment]
wait do i need to fork first? I forgot how it works

**Comment by Nightwing000** [comment]
I just cloned it on vscode so

**Comment by tejas-techstack** [comment]
yes okay so
1. create fork
2. push your changes to your own fork
3. create a pull request to the specified branch

**Comment by tejas-techstack** [comment]
you can also refer [contributing.md](https://github.com/acmpesuecc/SmartGC/blob/main/CONTRIBUTING.md)

**Comment by tejas-techstack** [comment]
!extend 20

**Comment by Nightwing000** [comment]
do you need to add time or can I still push?

**Comment by Nightwing000** [comment]
ah thanks

**Comment by tejas-techstack** [comment]
yea you should still be able to push and create the pull request dont worry about the time now

**Comment by tejas-techstack** [comment]
!deassign @Nightwing000

**Comment by tejas-techstack** [comment]
!assign @Nightwing000

**Comment by Nightwing000** [comment]
can you see it? going for dinner so

**Comment by tejas-techstack** [comment]
!extend 60

**Comment by tejas-techstack** [comment]
!deassign

**Comment by tejas-techstack** [comment]
!assign @Nightwing000

**Comment by Nightwing000** [comment]
Hi can you check the comments on the pull request

**Comment by tejas-techstack** [comment]
!deassign

**Comment by Nightwing000** [comment]
Hi apparently i'm not deassigned unable to get assigned new issues

**Comment by tejas-techstack** [comment]
!deassign

**Comment by tejas-techstack** [comment]
im so sorry i have fixed that

**Comment by tejas-techstack** [comment]
you can work on other issues now

**Comment by Nightwing000** [comment]
thanks
