### ISSUE TITLE
Check for syntax errors and correct allocations before injection

### ISSUE THREAD

**Issue by tejas-techstack** [acmpesuecc/SmartGC#3]
The python parser does not check for syntax errors and such for the c code.
this can create situations where even though the allocation is improper a free statement is injected.
Handle this by first compiling the code, if there is an error in the compilation only return the error, but if the compilation passes 
do the injections.

**Comment by gma4040** [comment]
please assign this to me

**Comment by tejas-techstack** [comment]
alright im assigning you @gma4040 
i will be giving you 1 hr min as of now, based on your progress we shall extend the time if needed

**Comment by tejas-techstack** [comment]
!assign @gma4040 60

**Comment by gaganbrwj** [comment]
please assign this to me

**Comment by tejas-techstack** [comment]
when you are done and want to create a pullrequest please send me a message so that i can confirm which branch you will need to create the pull request to @gma4040

**Comment by gma4040** [comment]
Im going to dinner now could you please extend time

**Comment by tejas-techstack** [comment]
!extend 60

**Comment by tejas-techstack** [comment]
!deassign

**Comment by tejas-techstack** [comment]
!assign @gma4040

**Comment by tejas-techstack** [comment]
i hope you have started working on it

**Comment by gma4040** [comment]
yes

**Comment by tejas-techstack** [comment]
hey, do you have any progress?

**Comment by gma4040** [comment]
working on it give me 10 minutes

**Comment by tejas-techstack** [comment]
alright sure i will extend your time then

**Comment by tejas-techstack** [comment]
!deassign

**Comment by tejas-techstack** [comment]
!assign @gma4040

**Comment by gma4040** [comment]
Im unable to solve this could you please unassign me

**Comment by tejas-techstack** [comment]
sure i will do that but you can run `!withdraw` to remove yourself

**Comment by tejas-techstack** [comment]
!deassign

**Comment by Harshinigrandhi2005** [comment]
can i get this assigned @tejas-techstack

**Comment by tejas-techstack** [comment]
!assign @Harshinigrandhi2005

**Comment by tejas-techstack** [comment]
!extend

**Comment by AkshayaR11** [comment]
can i get assigned to this

**Comment by tejas-techstack** [comment]
!assign @AkshayaR11 60

**Comment by tejas-techstack** [comment]
hey are you working on this?

**Comment by AyushChakraborty** [comment]
please assign me this @tejas-techstack

**Comment by tejas-techstack** [comment]
!assign @AyushChakraborty

**Comment by tejas-techstack** [comment]
@AyushChakraborty you might already be assigned to a different issue make sure you are deassigned from any issue before you can be assigned somewhere else

**Comment by AyushChakraborty** [comment]
yes I am working on other issue

**Comment by VulcanRaven737** [comment]
Hey can I please be assigned to this?
