### ISSUE TITLE
Same variable name, different scopes

### ISSUE THREAD

**Issue by tejas-techstack** [acmpesuecc/SmartGC#5]
As of right now if two variables with the same name are allocated in different scopes (say one in main function and another in a different function) , then only one reference is stored.

This can be solved by keeping track of the variables by using a hash map rather than using the variable names to keep track of the references.

**Comment by sampada115** [comment]
can you please assign me this

**Comment by tejas-techstack** [comment]
!assign @sampada115 60

**Comment by tejas-techstack** [comment]
alright im assigning you @sampada115 
i will be giving you 1 hr  as of now, based on your progress we shall extend the time if needed

**Comment by sampada115** [comment]
dinnerrrr timmmeee

**Comment by tejas-techstack** [comment]
!extend 60

**Comment by tejas-techstack** [comment]
i hope you are working on this

**Comment by sampada115** [comment]
yes

**Comment by sampada115** [comment]
till when do i have time?

**Comment by tejas-techstack** [comment]
i cant say for sure but you have another 30 minutes left as of now

**Comment by tejas-techstack** [comment]
do you have any progress, if you can show me some progress time can be extended

**Comment by sampada115** [comment]
i have submitted can you check one

**Comment by tejas-techstack** [comment]
i donot see the pull request, are you sure u created the pull request properly?

**Comment by sampada115** [comment]
i pushed the request and it showed me my username pushed time ago i asked someone for help and he said to wait for the mentor to check

**Comment by tejas-techstack** [comment]
which room and row are you sitting in?

**Comment by tejas-techstack** [comment]
or else if its easier come to room 001

**Comment by sampada115** [comment]
sem hall 1 5th row from the door

**Comment by sampada115** [comment]
i'll come

**Comment by tejas-techstack** [comment]
@sampada115 please check the comment in the pr

**Comment by tejas-techstack** [comment]
!deassign

**Comment by AkshayaR11** [comment]
can i get this assigned to me?

**Comment by tejas-techstack** [comment]
before i assign, are you using linux or windows system @AkshayaR11

**Comment by AkshayaR11** [comment]
windows

**Comment by tejas-techstack** [comment]
im sorry you will not actually be able to run the program, if you are ready to figure out a way to run it on windows i shall assign the issue, if you dont want to i shall not assign

**Comment by AkshayaR11** [comment]
Oh in that case dont assign it to me

**Comment by VulcanRaven737** [comment]
Hey can I get this assigned please?

**Comment by tejas-techstack** [comment]
!assign @VulcanRaven737 60

**Comment by VulcanRaven737** [comment]
Kindly have a look at the PR @tejas-techstack

**Comment by tejas-techstack** [comment]
!deassign
