### ISSUE TITLE
variable allocated in lower scope and passed to higher scope

### ISSUE THREAD

**Issue by tejas-techstack** [acmpesuecc/SmartGC#6]
If a variable is allocated in a lower scope and is returned to a higher scope, then the memory will need to be freed in the
higher scope.
eg:

```c
int * myFunc(){
  int *x = malloc(sizeof(int));
  *x = 15;
  return x;
}

int main(){
  int *valOfx = myFunc();
  printf("%d\n", x);
  // Free is to be injected here and valOfx is to be freed.
  return 0;
}
```

this requires keeping track of the variable through the scopes.
your job is to make sure that the memory is freed correctly in the higher scope

**Comment by H-Mudliar** [comment]
can you please assign this to me

**Comment by tejas-techstack** [comment]
alright im assigning you @H-Mudliar 
i will be giving you 1 hr 30 min as of now, based on your progress we shall extend the time if needed

**Comment by tejas-techstack** [comment]
!assign @H-Mudliar 90

**Comment by tejas-techstack** [comment]
when you are done and want to create a pullrequest please send me a message so that i can confirm which branch you will need to create the pull request to @H-Mudliar

**Comment by H-Mudliar** [comment]
> alright im assigning you @H-Mudliar i will be giving you 1 hr 30 min as of now, based on your progress we shall extend the time if needed

Im going for dinner now can you please extend time

**Comment by tejas-techstack** [comment]
!extend 60

**Comment by tejas-techstack** [comment]
i hope you are working on this

**Comment by tejas-techstack** [comment]
!deassign

**Comment by tejas-techstack** [comment]
!assign @H-Mudliar

**Comment by tejas-techstack** [comment]
@H-Mudliar Do you have any progress?

**Comment by tejas-techstack** [comment]
@H-Mudliar i am deassigning you so that others can work on this if they want

**Comment by tejas-techstack** [comment]
!deassign

**Comment by Nightwing000** [comment]
can i be assigned

**Comment by tejas-techstack** [comment]
!assign @Nightwing000 90

**Comment by tejas-techstack** [comment]
you have 1 and a half hour, if you are not able to finish within that time but have progress i will see and extend the time

**Comment by Nightwing000** [comment]
Thanks

**Comment by Nightwing000** [comment]
Hi so do you need it to free properly only in main or for any function of higher scope?

**Comment by Nightwing000** [comment]
also if just main is acceptable please tell how many points

**Comment by Nightwing000** [comment]
@tejas-techstack can you please tell so I can start implementing

**Comment by tejas-techstack** [comment]
hey im so sorry i was working on something else

**Comment by tejas-techstack** [comment]
yea so i will be able to give you only 200 points if you can successfully implement it for main alone
the max bounty is extremely hard because of multiple different higher scopes.

**Comment by Nightwing000** [comment]
ah no problem thank you so much

**Comment by tejas-techstack** [comment]
are you going to be working on it?

**Comment by Nightwing000** [comment]
yeah lemme see if I can implement the entire thing(not just main)

**Comment by tejas-techstack** [comment]
!deassign

**Comment by tejas-techstack** [comment]
!assign @Nightwing000

**Comment by Nightwing000** [comment]
I've made progress I think I'll be done after the performances(taking a break)

**Comment by tejas-techstack** [comment]
!assign @Nightwing000

**Comment by tejas-techstack** [comment]
@Nightwing000 were you able to run the program on windows, without libclang-dev?

**Comment by Nightwing000** [comment]
I downloaded llvm and it worked but I'm having issues with the check_alloc_term function my logic goes like finding only variables that contain main but yea it doesn't give the output still trying

**Comment by Nightwing000** [comment]
please let me know if you can see my pull request @tejas-techstack

**Comment by tejas-techstack** [comment]
hey sorry i was a bit busy

**Comment by tejas-techstack** [comment]
!deassign
